{{ $name := "graphql" }}
{{ $version := "v1" }}
{{ $fullName := printf "%s-%s-%s" .Release.Name $name $version }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-service
spec:
  {{- if .Values.nodePort }}
  type: NodePort
  {{- end }}
  selector:
    name: {{ $fullName }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      {{- if .Values.nodePort }}
      nodePort: 4000
      {{- end }}