kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
spec:    
  type: NodePort
  selector:
    app: {{ .Release.Name }}-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 80