{{ $name := "redis" }}
{{ $fullName := printf "%s-%s" .Release.Name $name }}
{{ $image := printf "%s-%s" .Chart.Name $name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-service
spec:
  selector:
    name: {{ $fullName }}
  {{- if .Values.nodePort }}
  type: NodePort
  {{- end }}
  ports:
    - name: http
      protocol: TCP
      port: 6379    
      {{- if .Values.nodePort }}
      nodePort: 6379
      {{- end }}