{{ $name := "rabbitmq" }}
{{ $fullName := printf "%s-%s" .Release.Name $name }}
{{ $image := printf "%s-%s" .Chart.Name $name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-service
spec:
  selector:
    name: {{ $fullName }}
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 15672    
      nodePort: 30002
    - name: amqp
      protocol: TCP
      port: 5672